---
extends: default

ignore: |
  build-docker-images/
  config/
  venv/
  collections/
  ansible-lint-venv/
  deploy.yml
  teardown.yml


rules:
  comments-indentation: false
  comments:
    min-spaces-from-content: 1
  braces:
    max-spaces-inside: 1
  octal-values:
    forbid-implicit-octal: true
    forbid-explicit-octal: true
  line-length:
    max: 120
  truthy:
    check-keys: false
  indentation:
    spaces: 2
    indent-sequences: true
  trailing-spaces: enable
