---
extends: default

ignore: |
  build-docker-images/
  config/
  deploy-wazuh.yml


rules:
  line-length:
    max: 120
  truthy:
    check-keys: false
  indentation:
    spaces: 2
    indent-sequences: true
  trailing-spaces: enable
