- name: Deploy Wazuh stack via Ansible
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    wazuh_api_password: "{{ lookup('env', 'WAZUH_API_PASSWORD') }}"
    wazuh_indexer_password: "{{ lookup('env', 'WAZUH_INDEXER_PASSWORD') }}"
    wazuh_dashboard_password: "{{ lookup('env', 'WAZUH_DASHBOARD_PASSWORD') }}"
    root_ca_cert: "{{ lookup('env', 'ROOT_CA_CERT') }}"
    root_ca_key: "{{ lookup('env', 'ROOT_CA_KEY') }}"
    root_ca_manager_cert: "{{ lookup('env', 'ROOT_CA_MANAGER_CERT') }}"
    root_ca_manager_key: "{{ lookup('env', 'ROOT_CA_MANAGER_KEY') }}"
    admin_cert: "{{ lookup('env', 'ADMIN_CERT') }}"
    admin_key: "{{ lookup('env', 'ADMIN_KEY') }}"
    indexer_cert: "{{ lookup('env', 'INDEXER_CERT') }}"
    indexer_key: "{{ lookup('env', 'INDEXER_KEY') }}"
    master_cert: "{{ lookup('env', 'MASTER_CERT') }}"
    master_key: "{{ lookup('env', 'MASTER_KEY') }}"
    worker_cert: "{{ lookup('env', 'WORKER_CERT') }}"
    worker_key: "{{ lookup('env', 'WORKER_KEY') }}"
    dashboard_cert: "{{ lookup('env', 'DASHBOARD_CERT') }}"
    dashboard_key: "{{ lookup('env', 'DASHBOARD_KEY') }}"
    nginx_cert: "{{ lookup('env', 'NGINX_CERT') }}"
    nginx_key: "{{ lookup('env', 'NGINX_KEY') }}"

  tasks:
    - name: Ensure Docker swarm is initialized
      community.docker.docker_swarm:
        state: present
        advertise_addr: 127.0.0.1

    - name: Create Docker swarm secrets (certs & keys)
      community.docker.docker_secret:
        name: "{{ item.name }}"
        data: "{{ item.data | b64decode }}"
        state: present
      loop:
        - { name: "root-ca.pem", data: "{{ root_ca_cert }}" }
        - { name: "root-ca.key", data: "{{ root_ca_key }}" }
        - { name: "root-ca-manager.pem", data: "{{ root_ca_manager_cert }}" }
        - { name: "root-ca-manager.key", data: "{{ root_ca_manager_key }}" }
        - { name: "admin.pem", data: "{{ admin_cert }}" }
        - { name: "admin-key.pem", data: "{{ admin_key }}" }
        - { name: "wazuh1.indexer.pem", data: "{{ indexer_cert }}" }
        - { name: "wazuh1.indexer-key.pem", data: "{{ indexer_key }}" }
        - { name: "wazuh.master.pem", data: "{{ master_cert }}" }
        - { name: "wazuh.master-key.pem", data: "{{ master_key }}" }
        - { name: "wazuh.worker.pem", data: "{{ worker_cert }}" }
        - { name: "wazuh.worker-key.pem", data: "{{ worker_key }}" }
        - { name: "wazuh.dashboard.pem", data: "{{ dashboard_cert }}" }
        - { name: "wazuh.dashboard-key.pem", data: "{{ dashboard_key }}" }
        - { name: "nginx.pem", data: "{{ nginx_cert }}" }
        - { name: "nginx.key", data: "{{ nginx_key }}" }

    - name: Remove old Wazuh stack if it exists
      community.docker.docker_stack:
        name: wazuh
        state: absent

    - name: Deploy Wazuh stack
      community.docker.docker_stack:
        name: wazuh
        state: present
        compose:
          - stack.yml

    - name: Wait for API to be ready
      ansible.builtin.uri:
        url: "https://127.0.0.1:443/api"
        method: GET
        validate_certs: false
      register: wazuh_api
      retries: 30
      delay: 10
      until: wazuh_api.status == 200
