---
- name: Deploy Wazuh stack via Ansible
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Initialize Docker swarm
      ansible.builtin.shell: docker swarm init --advertise-addr 127.0.0.1 || true

    - name: Remove old Wazuh stack
      ansible.builtin.shell: docker stack rm wazuh || true

    - name: Deploy Wazuh stack
      shell: docker stack deploy -c stack.yml wazuh

    - name: Wait for API to be ready
      ansible.builtin.shell: |
        echo "Waiting for Wazuh services to be healthy..."
        until curl -k -s https://127.0.0.1:443/api >/dev/null; do
              
          echo "Waiting..."
          sleep 10
        done
        echo "Wazuh stack is ready"