- name: Deploy Wazuh stack via Ansible
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    wazuh_api_password: "{{ lookup('env', 'WAZUH_API_PASSWORD') }}"
    wazuh_indexer_password: "{{ lookup('env', 'WAZUH_INDEXER_PASSWORD') }}"
    wazuh_dashboard_password: "{{ lookup('env', 'WAZUH_DASHBOARD_PASSWORD') }}"
    root_ca_cert: "{{ lookup('env', 'ROOT_CA_CERT') }}"
    root_ca_key: "{{ lookup('env', 'ROOT_CA_KEY') }}"
    root_ca_manager_cert: "{{ lookup('env', 'ROOT_CA_MANAGER_CERT') }}"
    root_ca_manager_key: "{{ lookup('env', 'ROOT_CA_MANAGER_KEY') }}"
    admin_cert: "{{ lookup('env', 'ADMIN_CERT') }}"
    admin_key: "{{ lookup('env', 'ADMIN_KEY') }}"
    indexer_cert: "{{ lookup('env', 'INDEXER_CERT') }}"
    indexer_key: "{{ lookup('env', 'INDEXER_KEY') }}"
    master_cert: "{{ lookup('env', 'MASTER_CERT') }}"
    master_key: "{{ lookup('env', 'MASTER_KEY') }}"
    worker_cert: "{{ lookup('env', 'WORKER_CERT') }}"
    worker_key: "{{ lookup('env', 'WORKER_KEY') }}"
    dashboard_cert: "{{ lookup('env', 'DASHBOARD_CERT') }}"
    dashboard_key: "{{ lookup('env', 'DASHBOARD_KEY') }}"

  tasks:
    - name: Initialize Docker swarm
      ansible.builtin.shell: docker swarm init --advertise-addr 127.0.0.1 || true

    - name: Create Docker swarm secrets
      ansible.builtin.shell: |
        echo "{{ root_ca_cert }}"        | base64 -d | docker secret create root-ca.pem -
        echo "{{ root_ca_key }}"         | base64 -d | docker secret create root-ca.key -
        echo "{{ root_ca_manager_cert }}"| base64 -d | docker secret create root-ca-manager.pem -
        echo "{{ root_ca_manager_key }}" | base64 -d | docker secret create root-ca-manager.key -
        echo "{{ admin_cert }}"          | base64 -d | docker secret create admin.pem -
        echo "{{ admin_key }}"           | base64 -d | docker secret create admin-key.pem -
        echo "{{ indexer_cert }}"        | base64 -d | docker secret create wazuh1.indexer.pem -
        echo "{{ indexer_key }}"         | base64 -d | docker secret create wazuh1.indexer-key.pem -
        echo "{{ master_cert }}"         | base64 -d | docker secret create wazuh.master.pem -
        echo "{{ master_key }}"          | base64 -d | docker secret create wazuh.master-key.pem -
        echo "{{ worker_cert }}"         | base64 -d | docker secret create wazuh.worker.pem -
        echo "{{ worker_key }}"          | base64 -d | docker secret create wazuh.worker-key.pem -
        echo "{{ dashboard_cert }}"      | base64 -d | docker secret create wazuh.dashboard.pem -
        echo "{{ dashboard_key }}"       | base64 -d | docker secret create wazuh.dashboard-key.pem -
      register: secret_creation
      ignore_errors: yes

    - name: Show secret creation output
      ansible.builtin.debug:
        var: secret_creation.stdout_lines

    - name: Remove old Wazuh stack if it exists
      ansible.builtin.shell: docker stack rm wazuh || true

    - name: Deploy Wazuh stack
      shell: docker stack deploy -c stack.yml wazuh

    - name: Wait for API to be ready
      ansible.builtin.shell: |
        echo "Waiting for Wazuh services to be healthy..."
        until curl -k -s https://127.0.0.1:443/api >/dev/null; do
          echo "Waiting..."
          sleep 10
        done
        echo "Wazuh stack is ready"
