---
- name: Deploy Wazuh stack via Ansible
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Initialize Docker swarm
      ansible.builtin.shell: docker swarm init --advertise-addr 127.0.0.1 || true

    - name: Remove old Wazuh stack
      ansible.builtin.shell: docker stack rm wazuh || true

    - name: Deploy Wazuh stack
      shell: docker stack deploy -c stack.yml wazuh