---
- name: Teardown Wazuh stack via Ansible
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    ansible_python_interpreter: "{{ playbook_dir }}/ansible-venv/bin/python"


  tasks:
    - name: Remove Wazuh stack
      community.docker.docker_stack:
        name: wazuh
        state: absent

    - name: Remove Docker secrets
      community.docker.docker_secret:
        name: "{{ item }}"
        state: absent
      loop:
        - root-ca.pem
        - root-ca.key
        - root-ca-manager.pem
        - root-ca-manager.key
        - admin.pem
        - admin-key.pem
        - wazuh1.indexer.pem
        - wazuh1.indexer-key.pem
        - wazuh.master.pem
        - wazuh.master-key.pem
        - wazuh.worker.pem
        - wazuh.worker-key.pem
        - wazuh.dashboard.pem
        - wazuh.dashboard-key.pem
        - nginx.pem
        - nginx.key

    - name: Optionally leave Docker swarm clean
      community.docker.docker_swarm:
        state: absent
        force: true
