name: Wazuh CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Pull official Wazuh images
        run: |
          docker pull wazuh/wazuh-manager:4.12.0
          docker pull wazuh/wazuh-indexer:4.12.0
          docker pull wazuh/wazuh-dashboard:4.12.0

      - name: Scan Wazuh Manager image with Trivy
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: wazuh/wazuh-manager:4.12.0
          format: table
          severity: CRITICAL,HIGH
          exit-code: 1
          scanners: vuln

      - name: Scan Wazuh Indexer image with Trivy
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: wazuh/wazuh-indexer:4.12.0
          format: table
          severity: CRITICAL,HIGH
          exit-code: 1
          scanners: vuln

      - name: Scan Wazuh Dashboard image with Trivy
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: wazuh/wazuh-dashboard:4.12.0
          format: table
          severity: CRITICAL,HIGH
          exit-code: 1
          scanners: vuln
