name: Wazuh CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install docker-compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose

      - name: Build wazuh images
        run: |
          chmod +x build-docker-images/build-images.sh
          ./build-docker-images/build-images.sh

      - name: Scan Wazuh Manager image with Trivy
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: wazuh/wazuh-manager:4.12.0
          format: table
          severity: CRITICAL,HIGH
          exit-code: 1

      - name: Scan Wazuh Indexer image with Trivy
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: wazuh/wazuh-indexer:4.12.0
          format: table
          severity: CRITICAL,HIGH
          exit-code: 1

      - name: Scan Wazuh Dashboard image with Trivy
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: wazuh/wazuh-dashboard:4.12.0
          format: table
          severity: CRITICAL,HIGH
          exit-code: 1
