---
name: Lint Checks

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    outputs:
      lint_status: ${{ steps.lint_outcome.outputs.status }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Create venv and install linters
        run: |
          python3 -m venv ./ansible-lint-venv
          source ./ansible-lint-venv/bin/activate
          pip install --upgrade pip
          pip install yamllint ansible-lint

      - name: Run yamllint
        id: lint_outcome
        run: |
          source ./ansible-lint-venv/bin/activate
          yamllint . --strict

      - name: Run ansible-lint
        run: |
          source ./ansible-lint-venv/bin/activate
          ansible-lint -c .ansible-lint.yml deploy-wazuh.yml --nocolor

      - name: Cleanup venv
        if: always()
        run: rm -rf ./ansible-lint-venv
